# Generated by Django 6.1 on 2026-08-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('model_year', models.IntegerField()),
                ('plate', models.CharField(max_length=60)),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
