# Generated by Django 6.1 on 2026-08-20 21:34

import django.core.validators
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do carro')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('license_plate', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Informe uma placa válida (ex: ABC-1234 ou ABC1D23).', regex='^[A-Za-z]{3}-?\\d[A-Za-z0-9]\\d{2}$')], verbose_name='Placa')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacidade de passageiros')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('on_trip', 'Em viagem'), ('maintenance', 'Em manutenção'), ('inactive', 'Inativo')], default='available', max_length=20, verbose_name='Status')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=vehicles.models.vehicle_photo_path, verbose_name='Foto do carro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
