# Generated by Django 6.1 on 2026-08-20 21:59

from django.db import migrations


def copy_legacy_models_to_brands(apps, schema_editor):
    Brand = apps.get_model('vehicles', 'Brand')
    Vehicle = apps.get_model('vehicles', 'Vehicle')

    for vehicle in Vehicle.objects.exclude(model='').iterator():
        brand, _ = Brand.objects.get_or_create(name=vehicle.model)
        if vehicle.brand_id is None:
            vehicle.brand_id = brand.pk
            vehicle.save(update_fields=['brand'])


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_brand_vehicle_brand'),
    ]

    operations = [
        migrations.RunPython(copy_legacy_models_to_brands, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
    ]
