# Generated by Django 6.1 on 2026-08-20 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Ano')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Último número emitido')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, editable=False, max_length=15, unique=True, verbose_name='Protocolo')),
                ('department', models.CharField(max_length=100, verbose_name='Setor')),
                ('purpose', models.CharField(max_length=255, verbose_name='Atividade')),
                ('origin', models.CharField(max_length=150, verbose_name='Origem')),
                ('destination', models.CharField(max_length=150, verbose_name='Destino')),
                ('date', models.DateField(verbose_name='Data da viagem')),
                ('departure_time', models.TimeField(verbose_name='Horário de saída')),
                ('expected_return', models.DateTimeField(verbose_name='Previsão de retorno')),
                ('passenger_count', models.PositiveSmallIntegerField(verbose_name='Quantidade de passageiros')),
                ('status', models.CharField(choices=[('pending', 'Pendente de aprovação'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo da rejeição')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trips', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_driver', to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.PROTECT, related_name='requested_trips', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
